### ISSUE TITLE
Responsive - Services - Scrolling Ability; see descriptions 

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/In-Motion-2015#28]
There is no way to navigate through the services when you in the inner page except scrolling to the top or bottom of the pages. Can we make the header menu a sticky menu in responsive so the logo, menu and Facebook icon are always visible when scrolling through the services?

**Comment by hemantcci** [comment]
When fix the menu it will no scroll with with screen on mobile this is disadvantage of fixed menu when menu is long to fit the screen.
